### ISSUE TITLE
Sequence for deletion

### ISSUE THREAD

**Issue by FACOLOMBANI** [crossplane-contrib/function-sequencer#23]
### What problem are you facing?

On creation the sequence is respected but on deletion there is no sequence and i am encountering issues with some of the components.

### How could this Function help solve your problem?

can there be a sequence for deletion? in my case it would be the previously defined sequence but in reverse order.

**Comment by fernandezcuesta** [comment]
Hi, you can leverage [Usages](https://docs.crossplane.io/latest/concepts/usages/) for ordered deletion.

**Comment by FACOLOMBANI** [comment]
Usages works well thanks
